<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\Defra.Trade.API.Daera.Certificates.Ehco.BlobClient\Defra.Trade.API.Daera.Certificates.Ehco.BlobClient.csproj" />
	</ItemGroup>
</Project>
